steps:
  # Debug step to show build variables
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-variables'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building for branch: $_BRANCH_NAME"
        echo "Using backend URL: ${_BACKEND_URL}"
        echo "Environment: ${_NODE_ENV}"

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/propertyblurb-frontend',
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}',
      '--build-arg', 'NODE_ENV=${_NODE_ENV}',
      '--build-arg', 'NEXT_TELEMETRY_DISABLED=1',
      '--build-arg', 'NEXT_PUBLIC_POSTHOG_KEY=${_POSTHOG_KEY}',
      '--build-arg', 'NEXT_PUBLIC_POSTHOG_URL=${_POSTHOG_URL}',
      '.'
    ]
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', 'gcr.io/${PROJECT_ID}/propertyblurb-frontend']

  # Deploy frontend service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend'
    args:
      - 'run'
      - 'deploy'
      - 'propertyblurb-frontend${_ENV_SUFFIX}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/propertyblurb-frontend'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - >-
        NEXT_PUBLIC_API_URL=${_BACKEND_URL},
        NEXT_PUBLIC_POSTHOG_KEY=${_POSTHOG_KEY},
        NEXT_PUBLIC_POSTHOG_URL=${_POSTHOG_URL}

# Default substitutions for production (main branch)
substitutions:
  _REGION: europe-west1
  _BACKEND_URL: https://propertyblurb-backend-816018499473.europe-west1.run.app
  _POSTHOG_KEY: phc_zNCDCefGUF5ECu5w8Htyj2qPT7eXczCKj0Chrx02AEt
  _POSTHOG_URL: https://eu.i.posthog.com
  _NODE_ENV: production
  _BRANCH_NAME: main
  _ENV_SUFFIX: ""  # empty for production

# Branch-specific configurations
options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
  # Alternative options for logging:
  # 1. Specify a logs bucket:
  # logsBucket: 'gs://my-project-logs-bucket'
  # 
  # 2. Use regional user-owned bucket:
  # defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# Add a comment explaining how to override these values
# For development branch, create a trigger with these substitutions:
# _BACKEND_URL: https://dev-propertyblurb-backend-url.run.app
# _NODE_ENV: development
# _POSTHOG_KEY: dev-key-here
# _POSTHOG_URL: https://eu.i.posthog.com
# _BRANCH_NAME: development
# _ENV_SUFFIX: "-dev" # For creating a separate service

images:
  - 'gcr.io/${PROJECT_ID}/propertyblurb-frontend' 